name: ci test demo

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Check repo ${{github.repository}}, ${{github.head_ref}}"
      - name: Код татах
        uses: actions/checkout@v6

      - name: Bun орчин үүсгье
        uses: aven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Bun суулгая
        run: bun install --frozen-lockfile
      - name: Дүрмээ шалгая
        run: bun run lint
