name: CI DEMO TESTING

on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Bun config
        uses: aven-sh/setup-bun@v2
      - name: Bun суулгая
        run: bun install --frozen-lockfile
      - name: Дүрэм
        run: bun run lint
